# Generated by Django 4.2.5 on 2026-02-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User'), ('RESTAURANT', 'Restaurant'), ('DELIVERY', 'Delivery')], default='USER', max_length=20),
        ),
    ]
