# Generated by Django 4.2.5 on 2026-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('RESTAURANT', 'Restaurant Owner'), ('DELIVERY', 'Delivery Partner'), ('MANAGER', 'Manager'), ('NONE', 'None')], default='NONE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
