# Generated by Django 4.2.5 on 2026-02-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_cart_created_by_cart_deleted_at_cart_deleted_by_and_more'),
        ('access', '0004_state_city_alter_address_city_alter_address_state'),
        ('swiggy_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
