# Generated by Django 4.2.5 on 2026-02-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_orders_customer_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='preparation_timestamo',
            new_name='preparation_timestamp',
        ),
    ]
