# Generated by Django 4.2.5 on 2026-02-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_alter_users_role'),
        ('delivery', '0005_rename_preparation_timestamo_orders_preparation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to='access.users'),
        ),
    ]
