# Generated by Django 4.2.5 on 2026-02-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='food_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
