# Generated by Django 4.2.5 on 2026-02-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup'), ('REACHED_RESTAURANT', 'Reached Restaurant'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
