# Generated by Django 4.2.5 on 2026-02-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='handover_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
