# Generated by Django 4.2.5 on 2026-02-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_orders_handover_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cutlery_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
