# Generated by Django 4.2.5 on 2026-02-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_deliverypartner_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='profile_image_url',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='food_image_url',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_partners/profiles/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/items/'),
        ),
    ]
