# Generated by Django 4.2.5 on 2026-02-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_remove_deliverypartner_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='food_image',
        ),
    ]
