# Generated by Django 4.2.5 on 2026-02-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0021_users_profile_image'),
        ('delivery', '0016_remove_deliverypartner_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.images'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='food_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.images'),
        ),
    ]
