# Generated by Django 4.2.5 on 2026-02-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_alter_users_role'),
        ('restaurants', '0002_cart_created_by_cart_deleted_at_cart_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to='access.users'),
        ),
    ]
