# Generated by Django 4.2.5 on 2026-02-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_category_image_url_alter_restaurant_city_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_both',
            field=models.BooleanField(default=False),
        ),
    ]
