# Generated by Django 4.2.5 on 2026-02-12 07:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_category_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food_item',
        ),
        migrations.AlterField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        # Fix for invalid geometry error: Remove old char field first, then add new PointField
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Latitude and Longitude', null=True, srid=4326),
        ),
    ]
