# Generated by Django 4.2.5 on 2026-02-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_cart_food_item_alter_cart_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
