# Generated by Django 4.2.5 on 2026-02-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_fooditem_description_fooditem_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_image_url',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='food_image_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='logo_image_url',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/coupons/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/food_items/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/banners/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/logos/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/'),
        ),
    ]
