# Generated by Django 4.2.5 on 2026-02-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_remove_category_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_image',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='food_image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
    ]
