# Generated by Django 4.2.5 on 2026-02-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0021_users_profile_image'),
        ('restaurants', '0013_remove_category_image_remove_coupon_coupon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_image', to='access.images'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.images'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_banner', to='access.images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_logo', to='access.images'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_image', to='access.images'),
        ),
    ]
