# Generated by Django 4.2.5 on 2026-01-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='auth_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('RESTAURANT', 'Restaurant'), ('DELIVERY', 'Delivery')], max_length=50),
        ),
    ]
