# Generated by Django 4.2.5 on 2026-02-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_userauth_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
