# Generated by Django 4.2.5 on 2026-02-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_userauth_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='auth_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('RESTAURANT', 'Restaurant'), ('DELIVERY', 'Delivery'), ('SUPERADMIN', 'Super Admin')], max_length=50),
        ),
    ]
