# Generated by Django 4.2.5 on 2026-02-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_state_city_alter_address_city_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User'), ('RESTAURANT', 'Restaurant')], max_length=20),
        ),
    ]
