# Generated by Django 4.2.5 on 2026-02-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_alter_users_phone_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User')], db_index=True, max_length=20),
        ),
    ]
