# Generated by Django 4.2.5 on 2026-02-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_type',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('DELIVERY_ADMIN', 'Delivery Admin'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User'), ('RESTAURANT', 'Restaurant'), ('DELIVERY', 'Delivery')], db_index=True, max_length=20),
        ),
    ]
