# Generated by Django 4.2.5 on 2026-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='admin_type',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
