# Generated by Django 4.2.5 on 2026-02-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_alter_users_admin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
