# Generated by Django 4.2.5 on 2026-02-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_alter_users_profile_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_tag',
            field=models.CharField(default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='access.users'),
        ),
    ]
