# Generated by Django 4.2.5 on 2026-02-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0013_remove_address_latitude_remove_address_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='admin_type',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('DELIVERY_PARTNER', 'Delivery Partner'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
