# Generated by Django 4.2.5 on 2026-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0014_alter_users_admin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='admin_type',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('DELIVERY_PARTNER', 'Delivery Partner'), ('USER', 'User')], db_index=True, max_length=20),
        ),
    ]
