# Generated by Django 4.2.5 on 2026-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0015_remove_users_admin_type_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('DELIVERY_ADMIN', 'Delivery Admin'), ('USER', 'User'), ('DELIVERY_PARTNER', 'Delivery Partner')], db_index=True, max_length=20),
        ),
    ]
