# Generated by Django 4.2.5 on 2026-02-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_fooditem_description_fooditem_rating'),
        ('access', '0016_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.fooditem'),
        ),
    ]
