# Generated by Django 4.2.5 on 2026-02-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0017_wishlist_restaurant_alter_wishlist_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/profiles/'),
        ),
    ]
