# Generated by Django 4.2.5 on 2026-02-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0019_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_image',
        ),
    ]
